version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda-events:al2-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-amazonlinux2"

  soundness:
    image: swift-aws-lambda-events:al2-5.9

  test:
    image: swift-aws-lambda-events:al2-5.9

  test-samples:
    image: swift-aws-lambda-events:al2-5.9

  shell:
    image: swift-aws-lambda-events:al2-5.9
