version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda-events:al2-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-amazonlinux2"

  soundness:
    image: swift-aws-lambda-events:al2-main

  test:
    image: swift-aws-lambda-events:al2-main

  test-samples:
    image: swift-aws-lambda-events:al2-main

  shell:
    image: swift-aws-lambda-events:al2-main
