version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda-events:al2-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-amazonlinux2"

  soundness:
    image: swift-aws-lambda-events:al2-5.10

  test:
    image: swift-aws-lambda-events:al2-5.10

  test-samples:
    image: swift-aws-lambda-events:al2-5.10

  shell:
    image: swift-aws-lambda-events:al2-5.10
