version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda-events:al2-5.9
    build:
      args:
        swift_version: "5.9"

  soundness:
    image: swift-aws-lambda-events:al2-5.9

  test:
    image: swift-aws-lambda-events:al2-5.9

  test-samples:
    image: swift-aws-lambda-events:al2-5.9

  shell:
    image: swift-aws-lambda-events:al2-5.9
